#!/bin/sh
#cleanup
rm -rf obj-dir
rm -f top_level.vcd

#run Verilator to translate Verilog into c++,including c++ testbench
verilator -Wall --cc --trace top_level.sv --exe counter_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop_level.mk Vtop_level

# run executable simulation file
obj_dir/Vtop_level