#!/bin/sh
#cleanup
rm -rf obj-dir
rm -f TOP.vcd

#run Verilator to translate Verilog into c++,including c++ testbench
verilator -Wall --cc --trace TOP.sv --exe counter_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VTOP.mk VTOP

# run executable simulation file
obj_dir/VTOP